services:
  mysql:
    image: mysql:8.4
    container_name: epi-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_epi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/01-database.sql:ro

  api:
    build: .
    container_name: epi-api
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: sistema_epi
    ports:
      - "3000:3000"

volumes:
  mysql_data: